# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip_to_rep', '0002_auto_20170425_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rep',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_to_rep.Zipcode'),
        ),
    ]
