# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip_to_rep', '0003_auto_20170425_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='location',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rep',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_to_rep.Zipcode'),
        ),
    ]
