# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip_to_rep', '0005_auto_20170425_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rep',
            old_name='location',
            new_name='recent_bill',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='rep',
            name='how_voted',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rep',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_to_rep.Zipcode'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
