# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip_to_rep', '0006_auto_20170425_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='how_voted',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='recent_bill',
        ),
        migrations.AlterField(
            model_name='rep',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_to_rep.Zipcode'),
        ),
    ]
