# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip_to_rep', '0010_auto_20170425_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_state', models.CharField(max_length=5)),
                ('dist_num', models.IntegerField()),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_to_rep.Zipcode')),
            ],
        ),
        migrations.AlterField(
            model_name='rep',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_to_rep.Zipcode'),
        ),
    ]
